low6_dbt_azureeastus2:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ""
      user: ""
      role: compute_role
      warehouse: compute_wh
      database: low6_azureeastus2
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 8
    prod:
      type: snowflake
      account: ""
      user: ""
      role: compute_role
      warehouse: compute_wh
      database: low6_azureeastus2
      schema: analytics
      threads: 8